# ==============================================================================
# C-ICAP Main Configuration File
# ==============================================================================
PidFile /var/run/c-icap/c-icap.pid
CommandsSocket /var/run/c-icap/c-icap.ctl
Timeout 300
MaxKeepAliveRequests 100
KeepAliveTimeout 600
StartServers 2
MaxServers 10
MinSpareThreads 5
MaxSpareThreads 20
ThreadsPerChild 10
MaxRequestsPerChild 0
Port 1344
User c-icap
Group c-icap
ServerAdmin admin@example.com
ServerName c-icap
TmpDir /tmp
MaxMemObject 131072
DebugLevel 1
Pipelining on
SupportBuggyClients off

# Modules & Services directories
ModulesDir /usr/lib/c_icap
ServicesDir /usr/lib/c_icap
TemplateDir /usr/share/c_icap/templates/
TemplateDefaultLanguage en
LoadMagicFile /etc/c-icap/c-icap.magic

ServerLog /var/log/c-icap/server.log
AccessLog /var/log/c-icap/access.log

# Access Control Lists
acl all src 0.0.0.0/0.0.0.0
acl PERMIT_REQUESTS type REQMOD RESPMOD
icap_access allow all PERMIT_REQUESTS

# Load SquidClamav Service (TCP INSTREAM Protocol - Zero shared filesystem volumes)
Service squidclamav squidclamav.so

# Map AVSCAN service alias expected by Oracle ORDS
ServiceAlias AVSCAN squidclamav?allow204=on&sizelimit=off&mode=simple
ServiceAlias avscan squidclamav?allow204=on&sizelimit=off&mode=simple
