-- ==============================================================================
-- Oracle Database Initialization Script for APEX Demo & File Uploads
-- ==============================================================================
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create DEMO application schema
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM all_users WHERE username = 'DEMO';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER DEMO IDENTIFIED BY "DemoPassword123!4" QUOTA UNLIMITED ON USERS';
        EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE SYNONYM TO DEMO';
        EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO DEMO';
    END IF;
END;
/

-- Create Table for Uploaded & Scanned Files in DEMO schema
DECLARE
    v_table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_count FROM all_tables WHERE owner = 'DEMO' AND table_name = 'DEMO_FILES';
    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE DEMO.DEMO_FILES (
                ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                FILENAME    VARCHAR2(500) NOT NULL,
                MIME_TYPE   VARCHAR2(255),
                FILE_SIZE   NUMBER,
                FILE_BLOB   BLOB,
                UPLOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                STATUS      VARCHAR2(50) DEFAULT ''SCANNED_CLEAN''
            )
        ';
    END IF;
END;
/

COMMIT;
